services:
  - name: app
    type: web
    build:
      dockerfilePath: ./Dockerfile
    env:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://{{fromDatabase("controle_restaurante").host}}:5432/controle_restaurante
      SPRING_DATASOURCE_USERNAME: {{fromDatabase("controle_restaurante").username}}
      SPRING_DATASOURCE_PASSWORD: {{fromDatabase("controle_restaurante").password}}

databases:
  - name: controle_restaurante
    database: postgres
    plan: free
