services:
  - name: app
    type: web
    build:
      dockerfilePath: ./Dockerfile
    env:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cv45qq3qf0us73b62rug-a.render.com:5432/controle_restaurante
      SPRING_DATASOURCE_USERNAME: controle_restaurante
      SPRING_DATASOURCE_PASSWORD: 7qNixtizxbBFLe8nk5RTEfScTLVjVbT9
    ports:
      - "8080:8080"
