services:
  - type: database
    name: db
    env: postgresql
    plan: free
    disk: 1GB
    database_url: postgres://myuser:secret@db:5432/mydatabase
    health_check:
      path: "/"
      protocol: HTTP
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  - type: web
    name: app
    env: java
    build:
      dockerfile_path: .  # Caminho do seu Dockerfile para a aplicação
    plan: free
    disk: 1GB
    env_vars:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: postgres://myuser:secret@db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db
    ports:
      - "8080"  # A porta da sua aplicação
    health_check:
      path: "/"
      protocol: HTTP
      interval: 10s
      retries: 5
