services:
  - type: web
    name: spring-app
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cv45qq3qf0us73b62rug-a:5432/controle_restaurante
      - key: SPRING_DATASOURCE_USERNAME
        value: controle_restaurante
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false