services:
  - name: db
    type: database  # Especifica que é um banco de dados
    databaseName: mydatabase
    plan: free
    databaseType: postgresql
    ipAllowList: []  # Permite conexões apenas de dentro do Render
    envVars:
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_PASSWORD
        value: secret

  - name: app
    type: web
    env: docker
    repo: https://github.com/seu-usuario/seu-repositorio
    branch: main  # Ajuste para o nome correto da branch
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: local
      - key: SPRING_DATASOURCE_URL
        fromService:
          name: db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        value: myuser
      - key: SPRING_DATASOURCE_PASSWORD
        value: secret
    plan: free
    autoDeploy: true
