services:
  - name: db
    type: web
    env: docker
    plan: free
    dockerCommand: ""
    image: postgres:13
    envVars:
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_PASSWORD
        value: secret
      - key: POSTGRES_DB
        value: mydatabase
    healthCheckPath: "/"

  - name: app
    type: web
    env: docker
    plan: free
    repo: https://github.com/seu-usuario/seu-repositorio
    branch: main  # Ajuste conforme necessário
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: local
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db:5432/mydatabase
      - key: SPRING_DATASOURCE_USERNAME
        value: myuser
      - key: SPRING_DATASOURCE_PASSWORD
        value: secret
    autoDeploy: true
