services:
  - name: db
    type: database
    database: postgres
    plan: free
    env:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    healthcheck:
      path: /health
      interval: 10s
      retries: 5
      timeout: 10s

  - name: app
    type: web
    build:
      dockerfilePath: ./Dockerfile
    env:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db
    ports:
      - "8080:8080"
