databases:
  - name: mydatabase
    databaseName: mydatabase
    user: myuser
    ipAllowList: [] # Permite apenas conexões pela rede privada

services:
  - type: web
    name: app
    runtime: docker
    plan: standard
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: local
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mydatabase
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mydatabase
          property: password